trunk/protected/modules/translate/controllers/TranslateController.php
<?php
class TranslateController extends TranslateBaseController{
	public function actionIndex(){
        if(isset($_POST['Message'])){
            foreach($_POST['Message'] as $id=>$message){
                if(empty($message['translation']))
                    continue;
                $model=new Message();
                $message['id']=$id;
                $model->setAttributes($message);
                $model->save();
            }
            $this->redirect(Yii::app()->getUser()->getReturnUrl());
        }
        if(($referer=Yii::app()->getRequest()->getUrlReferrer()) && $referer!==$this->createUrl('index'))
            Yii::app()->getUser()->setReturnUrl($referer);
        $translator=TranslateModule::translator();
        $key=$translator::ID."-missing";
        if(isset($_POST[$key]))
            $postMissing=$_POST[$key];
        elseif(Yii::app()->getUser()->hasState($key))
            $postMissing=Yii::app()->getUser()->getState($key);
        
        if(count($postMissing)){
            Yii::app()->getUser()->setState($key,$postMissing); 
            $cont=0;
            foreach($postMissing as $id=>$message){
                $models[$cont]=new Message;
                $models[$cont]->setAttributes(array('id'=>$id,'language'=>$message['language']));
                $cont++;
            }
        }else{
            $this->renderText(TranslateModule::t('All messages translated'));
            Yii::app()->end();
        }
        
        $data=array('messages'=>$postMissing,'models'=>$models);
        
        $this->render('index',$data);
	}
    function actionSet(){
        $translator=TranslateModule::translator();
        if(Yii::app()->getRequest()->getIsPostRequest()){
            TranslateModule::translator()->setLanguage($_POST[$translator::ID]);
            $this->redirect(Yii::app()->getRequest()->getUrlReferrer());
        }else
            throw new CHttpException(400);
    }
    function actionGoogletranslate(){
        if(Yii::app()->getRequest()->getIsPostRequest()){
            $translation=TranslateModule::translator()->googleTranslate($_POST['message'],$_POST['language'],$_POST['sourceLanguage']);
            if(is_array($translation))
                echo CJSON::encode($translation);
            else
                echo $translation;
        }else
            throw new CHttpException(400);
    }
    
}

trunk/protected/modules/translate/views/translate/_form.php
<?php

$translator=TranslateModule::translator();
$languageKey=$translator::ID;
$id=$data->id;
$message=$messages[$id];

if($google)
    $tagId="{$languageKey}-{$id}";

echo CHtml::openTag('tr');

echo CHtml::tag('td',array(),
    CHtml::tag('span',array('margin:0 5px'),$message['category'])
);
echo CHtml::tag('td',array(),
    CHtml::tag('span',array(
            'margin:0 5px',
            'class'=>$languageKey."-google-message"
        ),$message['message']
    )
);
echo CHtml::tag('td',array(),
    CHtml::activeTextArea($data,"[$id]translation",array('id'=>$google ? $tagId : null,'class'=>"{$languageKey}-google-translation",'cols'=>35,'rows'=>2)).
    CHtml::activeHiddenField($data,"[$id]language")
);
if($google){
    echo CHtml::tag('td',array(),
            CHtml::ajaxLink(TranslateModule::t('Translate'),
                $this->createUrl('translate/googletranslate'),
                array(
                    'type'=>'post',
                    'data'=>array(
                        'message'=>$message['message'],
                        'language'=>Yii::app()->getLanguage(),
                        'sourceLanguage'=>Yii::app()->sourceLanguage
                    ),
                    'success'=>"js:function(response){
                        \$('#{$tagId}').val(response);
                        \$('#{$tagId}-button').hide();
                    }",
                    'error'=>'js:function(xhr){alert(xhr.responseText);}',
                ),
                array(
                    'margin:0 5px',
                    'class'=>"{$languageKey}-google-button",
                    'id'=>$tagId.'-button',
                )
            )
    );
}
echo CHtml::closeTag('tr');

trunk/protected/modules/translate/views/translate/index.php
<?php 
    $language=TranslateModule::translator();
    $languageKey=$language::ID; 
    
    $google=!empty(TranslateModule::translator()->googleApiKey) ? true : false;
?>
<h2><?php echo TranslateModule::t('Translate to {lang}',array('{lang}'=>$language->acceptedLanguages[$language->getLanguage()]));?></h2>
<?php
    if($google){
        echo CHtml::link(TranslateModule::t('Translate all with google translate'),"#",array('id'=>$languageKey."-google-translateall"));
        echo CHtml::script(
            "\$('#{$languageKey}-google-translateall').click(function(){
                var messages=[];\$('.{$languageKey}-google-message').each(function(count){
                    messages[count]=$(this).html();
                });".
                CHtml::ajax(array(
                    'url'=>$this->createUrl('translate/googletranslate'),
                    'type'=>'post',
                    'dataType'=>"json",
                    'data'=>array(
                        'language'=>Yii::app()->getLanguage(),
                        'sourceLanguage'=>Yii::app()->sourceLanguage,
                        'message'=>'js:messages'
                    ),
                    'success'=>"js:function(response){
                        \$('.{$languageKey}-google-translation').each(function(count){
                            $(this).val(response[count]);
                        });
                        \$('.{$languageKey}-google-button,#{$languageKey}-google-translateall').hide();
                    }",
                    'error'=>'js:function(xhr){alert(xhr.statusText);}',
                ))."
                return false;
            });
        ");
        if(Yii::app()->getRequest()->isAjaxRequest){
            echo CHtml::script("
                $('#".$languageKey.'-pager'." a').click(function(){
                    \$dialog=$('#".$languageKey.'-dialog'."').load($(this).attr('href'));
                    return false;
                });
            ");
        }
    }
?>
<div class="form">
    <?php echo CHtml::beginForm(); ?>
    <table>
        <thead>
            <th><?php echo MessageSource::model()->getAttributeLabel('category'); ?></th>
            <th><?php echo MessageSource::model()->getAttributeLabel('message'); ?></th>
            <th><?php echo Message::model()->getAttributeLabel('translation');?></th>
            <?php echo $google ? CHtml::tag('th') : null;?>
        </thead>
        <tbody>
        <?php
            $this->widget('zii.widgets.CListView', array(
                'dataProvider'=>new CArrayDataProvider($models),
                'pager'=>array(
                    'id'=>$languageKey.'-pager',
                    'class'=>'CLinkPager',
                ),
                'viewData'=>array(
                    'messages'=>$messages,
                    'google'=>$google,
                ),
                'itemView'=>'_form',
            ));
        ?>
        </tbody>
    </table>
    <?php echo CHtml::submitButton(TranslateModule::t('Translate'));?>
    <?php echo CHtml::endForm()?>
</div>